"""Add BookCopy table

Revision ID: 15b616abf313
Revises: 720cfca8c164
Create Date: 2026-08-01 19:42:53.841955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b616abf313'
down_revision = '720cfca8c164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_copies',
    sa.Column('copy_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ISSUED', 'RESERVED', 'LOST', name='copy_status'), nullable=False),
    sa.Column('shelf_location', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.PrimaryKeyConstraint('copy_id'),
    sa.UniqueConstraint('accession_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_copies')
    # ### end Alembic commands ###
