"""add copy to reservations

Revision ID: 38b2ca3ce100
Revises: 72b9d3674bbe
Create Date: 2026-10-04 04:24:54.295282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38b2ca3ce100'
down_revision = '72b9d3674bbe'
branch_labels = None
depends_on = None


def upgrade():
    # Add copy_id temporarily as nullable so existing reservations can be migrated.
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('copy_id', sa.Integer(), nullable=True)
        )

    # Existing reservation belongs to book_id=2, whose copy_id is 2.
    op.execute(
        "UPDATE reservations "
        "SET copy_id = 2 "
        "WHERE reservation_id = 1"
    )

    # Make copy_id required and add the foreign key.
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column(
            'copy_id',
            existing_type=sa.Integer(),
            nullable=False
        )

        batch_op.alter_column(
            'status',
            existing_type=sa.String(length=20),
            type_=sa.Enum(
                'ACTIVE',
                'FULFILLED',
                'CANCELLED'
            ),
            existing_nullable=False
        )

        batch_op.create_foreign_key(
            None,
            'book_copies',
            ['copy_id'],
            ['copy_id']
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVE', 'FULFILLED', 'CANCELLED'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('copy_id')

    # ### end Alembic commands ###
