"""Add fine_paid column

Revision ID: 4d29d1b8d693
Revises: e4c4993bafd2
Create Date: 2026-08-01 22:06:58.802947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d29d1b8d693'
down_revision = 'e4c4993bafd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fine_paid', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_transactions', schema=None) as batch_op:
        batch_op.drop_column('fine_paid')

    # ### end Alembic commands ###
