"""Add Author model

Revision ID: 516b9873ade7
Revises: 905b562514cf
Create Date: 2026-08-01 18:05:27.854126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516b9873ade7'
down_revision = '905b562514cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=150), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('author_id'),
    sa.UniqueConstraint('author_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###
