"""Add Category model

Revision ID: 63061e128e69
Revises: 516b9873ade7
Create Date: 2026-08-01 18:14:23.174758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63061e128e69'
down_revision = '516b9873ade7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
